-- ============================================================================
-- 02_RAW_TABLES.SQL - Domain-specific typed table schemas
-- ============================================================================
USE DATABASE PALM_OIL_TRADING;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW.PLANTATIONS (
  PLANTATION_ID VARCHAR(20) NOT NULL, PLANTATION_NAME VARCHAR(200), PROVINCE VARCHAR(50), AREA_HA FLOAT, AGE_YEARS INT, VARIETY VARCHAR(30), CERTIFICATION VARCHAR(50), YIELD_LAST_YEAR FLOAT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.HARVESTS (
  HARVEST_ID VARCHAR(30) NOT NULL, PLANTATION_ID VARCHAR(20), HARVEST_DATE DATE, FFB_TONNES FLOAT, RIPE_PCT FLOAT, WORKERS INT, COST_PER_TONNE FLOAT, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.MILL_PROCESSING (
  PROCESS_ID VARCHAR(30) NOT NULL, PLANTATION_ID VARCHAR(20), PROCESS_DATE DATE, FFB_INPUT_TONNES FLOAT, CPO_OUTPUT_TONNES FLOAT, OER_PCT FLOAT, FFA_PCT FLOAT, QUALITY_GRADE VARCHAR(10), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.SHIPMENTS (
  SHIPMENT_ID VARCHAR(30) NOT NULL, ENTITY_ID VARCHAR(20), DESTINATION VARCHAR(100), SHIP_DATE DATE, QUANTITY FLOAT, UNIT VARCHAR(10), PRICE_PER_UNIT FLOAT, TOTAL_VALUE FLOAT, CARRIER VARCHAR(50), STATUS VARCHAR(20), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
