-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Commodity Trading Intelligence
-- ============================================================================
USE DATABASE PALM_OIL_TRADING;
USE SCHEMA ML;

-- ML.FORECAST: CPO_PRICE_FORECAST_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.CPO_PRICE_FORECAST_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.CPO_PRICE_TIMESERIES'),
  SERIES_COLNAME => 'CONTRACT_MONTH',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.CPO_PRICE_FORECAST_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.CPO_PRICE_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: POSITION_RISK_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.POSITION_RISK_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.POSITION_RISK_SUMMARY'),
  SERIES_COLNAME => 'DESK_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.POSITION_RISK_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.POSITION_RISK_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.POSITION_RISK_SUMMARY'), SERIES_COLNAME => 'DESK_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

