-- ============================================================================
-- 99_RESET.SQL — Reset Commodity Trading Intelligence to clean demo state
-- ============================================================================
USE DATABASE PALM_OIL_TRADING;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_STREAM_PRICES SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_RISK SUSPEND;
ALTER TASK IF EXISTS APP.TASK_FORECAST_PRICES SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.POSITION_RISK_SUMMARY REFRESH;
ALTER DYNAMIC TABLE CURATED.CPO_PRICE_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.HEDGE_EFFECTIVENESS REFRESH;
ALTER DYNAMIC TABLE CURATED.TRADING_PNL REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM PALM_OIL_TRADING.RAW.CPO_TRADES → 100000
-- SELECT COUNT(*) FROM PALM_OIL_TRADING.RAW.POSITIONS → 5000
-- SELECT COUNT(*) FROM PALM_OIL_TRADING.RAW.MDEX_PRICES → 50000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_FORECAST_PRICES RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_RISK RESUME;
ALTER TASK IF EXISTS APP.TASK_STREAM_PRICES RESUME;
